name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGothvpfX3ca1xZ_AA.fQxHKHaig7c"
            index: 0
          - recaptcha_token: "thr1.AAAAAGothw2B6rBYCy3DTw.eTAdsBa7QTA"
            index: 1
          - recaptcha_token: "thr1.AAAAAGothyKbtngHMoYYiw.4gYNVvQJnt4"
            index: 2
          - recaptcha_token: "thr1.AAAAAGothzsw2rYxlPFNkg.GT73bV7jFb4"
            index: 3
          - recaptcha_token: "thr1.AAAAAGoth08f_aQqpD8RgA.zyxUrojlXgE"
            index: 4
          - recaptcha_token: "thr1.AAAAAGoth2THqMJoOzO4LQ.YtUvzxHZ31M"
            index: 5
          - recaptcha_token: "thr1.AAAAAGoth3Yi50qvioKB3g.pE7ZTcyUfGY"
            index: 6
          - recaptcha_token: "thr1.AAAAAGoth4jZl_hLXmiBjQ.GAYuXdJZsHw"
            index: 7
          - recaptcha_token: "thr1.AAAAAGoth5mNxmAy7fEmCw.aaBtnGGlsp0"
            index: 8
          - recaptcha_token: "thr1.AAAAAGoth6pfBAO74wgAkA.V0WC8LPUxVY"
            index: 9
          - recaptcha_token: "thr1.AAAAAGoth8Frd8JF_ylBrQ.Q0z-D1PtZoE"
            index: 10
          - recaptcha_token: "thr1.AAAAAGoth-VzXEDGyj4aZw.eJUaqiKKUDc"
            index: 11
          - recaptcha_token: "thr1.AAAAAGoth_k5rHLjf_rhzg.AhG7pUkoonI"
            index: 12

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🧹 Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🚀 Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "👽"
