name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGou-LQEsJTIU7nibA.F3_F3jGtsyo"
            index: 0
          - recaptcha_token: "thr1.AAAAAGou-MmCzij3v6LHCw.wFYnChyeG9Y"
            index: 1
          - recaptcha_token: "thr1.AAAAAGou-NzlDi2tAHBB1w.NkHfPCDitTE"
            index: 2
          - recaptcha_token: "thr1.AAAAAGou-PGCg70f0ZT7vw.tcmz8-2BAh4"
            index: 3
          - recaptcha_token: "thr1.AAAAAGou-RxFaQ02-vYZLw.jptZqeI443Q"
            index: 4
          - recaptcha_token: "thr1.AAAAAGou-W6h7gsNLriUnQ.nPVORnmRMEA"
            index: 5
          - recaptcha_token: "thr1.AAAAAGou-Ycg_O-SHv0pRw.EMfWYGwi6n0"
            index: 6
          - recaptcha_token: "thr1.AAAAAGou-Z2RbbYKcvkYpQ.JTZf6twkvWQ"
            index: 7
          - recaptcha_token: "thr1.AAAAAGou-d0TMZcz0gRynw.hTX7wWdnpes"
            index: 8
          - recaptcha_token: "thr1.AAAAAGou-gAFQ4hdIyqEHQ.rpJHn39a0lQ"
            index: 9
          - recaptcha_token: "thr1.AAAAAGou-ha4_Ly7wli6Uw.cEAAUViPCZ0"
            index: 10
          - recaptcha_token: "thr1.AAAAAGou-iu4Xn3yyUXojA.MBiglQFl2m4"
            index: 11
          - recaptcha_token: "thr1.AAAAAGou-kCZat6EzNDqTQ.bZX8WqHRnIA"
            index: 12
          - recaptcha_token: "thr1.AAAAAGou-ldK2EcXLl1akg.z5HOFNO8CpM"
            index: 13
          - recaptcha_token: "thr1.AAAAAGou-nNtbKoqtAeidQ.y-U11ixq9v4"
            index: 14

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🚀 Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "👽"
