name: Host - Recaptcha Rooms - Group 2 - Restante

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts-restante
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGo1T3mjQ50ICVQebQ.tFFQJhMe1to"
            index: 15
          - recaptcha_token: "thr1.AAAAAGo1T4TVkcTAftsQJQ.8fTvU4Cch8k"
            index: 16
          - recaptcha_token: "thr1.AAAAAGo1T5bJfwyYyshHDQ.5MoFqKyqfCk"
            index: 17
          - recaptcha_token: "thr1.AAAAAGo1T6PNlafSTN5Zwg.baU0x-UNHdo"
            index: 18
          - recaptcha_token: "thr1.AAAAAGo1T7aFH-ATMMqJ_Q.1j5VbA4Ywbk"
            index: 19

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🧹 Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🚀 Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "👽"
