name: Ejecutar Bot de Haxball (200 Instancias)

on:
  workflow_dispatch:
    inputs:
      room_id:
        description: 'ID de la sala'
        required: true
        default: '-Rh4xBAYzkQ'
      room_password:
        description: 'Contraseña de la sala'
        required: false
        default: '#FFC'
      player_name:
        description: 'Nombre base del bot'
        required: true
        default: 'TLS-Bot'
      player_avatar:
        description: 'Avatar del bot'
        required: true
        default: '👽'

jobs:
  # Job inicial para generar una lista de 0 a 199 de forma dinámica
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      ids: ${{ steps.set-matrix.outputs.ids }}
    steps:
      - id: set-matrix
        run: |
          # Genera un array JSON del 0 al 199 usando console.log
          IDS=$(node -e "console.log(JSON.stringify(Array.from({length: 200}, (_, i) => i)))")
          echo "ids=$IDS" >> $GITHUB_OUTPUT

  # Este job se va a duplicar y ejecutar 200 veces en paralelo
  run-haxball:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Si una instancia falla, las otras siguen corriendo
      matrix:
        instance: ${{ fromJson(needs.generate-matrix.outputs.ids) }}

    steps:
    - name: Descargar código fuente
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar node-haxball
      run: npm install github:wxyz-abcd/node-haxball

    - name: Ejecutar Instancia del Bot
      env:
        ROOM_ID: ${{ github.event.inputs.room_id }}
        ROOM_PASSWORD: ${{ github.event.inputs.room_password }}
        PLAYER_NAME: ${{ github.event.inputs.player_name }}
        PLAYER_AVATAR: ${{ github.event.inputs.player_avatar }}
        INSTANCE_ID: ${{ matrix.instance }}
      run: node bots.js
